from . import test_church
from . import test_service
from . import test_minister
from . import test_members
from . import test_firsttimers
from . import test_tithes
from . import test_offering
from . import test_donation
from . import test_pledge
from . import test_lodgement